version: '3.8'
services:
  minio:
    image: minio/minio:RELEASE.2023-11-15T20-43-25Z
    command: server --console-address ":9001" /data{1...2}
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL:?}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL:?}
    volumes:
      - "/mnt/kiritan1:/data1"
      - "/mnt/kiritan2:/data2"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - minio
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_MINIO_LOG_DIR:?}:/logs/minio
      - ${NGINX_MINIO_CONSOLE_LOG_DIR:?}:/logs/minio-console
    ports:
      - ${NGINX_HOST_PORT:?}:80
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx
      - MINIO_DOMAIN=${NGINX_MINIO_DOMAIN:?}
      - MINIO_CONSOLE_DOMAIN=${NGINX_MINIO_CONSOLE_DOMAIN:?}

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
