services:
  minio:
    image: minio/minio:RELEASE.2024-07-15T19-02-30Z
    command: server --console-address ":9001" /data{1...2}
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:?}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:?}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL:?}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL:?}
      - MINIO_PROMETHEUS_URL=${MINIO_PROMETHEUS_URL:?}
      - MINIO_PROMETHEUS_AUTH_TOKEN=${MINIO_PROMETHEUS_AUTH_TOKEN}
    volumes:
      - "/mnt/kiritan1:/data1"
      - "/mnt/kiritan2:/data2"
    extra_hosts:
      - "minio.aoirint.com:${MINIO_AOIRINT_COM_IP_ADDRESS:?}"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: fluentd
      options:
        tag: docker.minio_aoirint_com.minio.{{.ID}}
        fluentd-async: "true"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - "./volumes/prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "./volumes/prometheus_data:/prometheus"
    depends_on:
      - minio
    logging:
      driver: fluentd
      options:
        tag: docker.minio_aoirint_com.prometheus.{{.ID}}
        fluentd-async: "true"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - minio
    volumes:
      - ./nginx_templates:/etc/nginx/templates
    ports:
      - ${NGINX_HOST_PORT:?}:80
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx
      - MINIO_DOMAIN=${NGINX_MINIO_DOMAIN:?}
      - MINIO_CONSOLE_DOMAIN=${NGINX_MINIO_CONSOLE_DOMAIN:?}
    logging:
      driver: fluentd
      options:
        tag: docker.minio_aoirint_com.nginx.{{.ID}}
        fluentd-async: "true"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
    logging:
      driver: fluentd
      options:
        tag: docker.minio_aoirint_com.cloudflared.{{.ID}}
        fluentd-async: "true"
